### ISSUE TITLE
复现代码出现问题？？

### ISSUE THREAD

**Issue by tongxiaozhong14** [Tianfang-Zhang/acm-pytorch#1]
亲爱的作者，非常感谢你分享acm的pytorch版本的代码？但是我将你的代码下载之后，在我的电脑上面复现，却出现了几个问题？？你可以给个联系方式吗？？我们一起探讨一下。如果不方便的话，您可以在github上面给我解答吗？？？
第1个问题就是：运行您的代码，同样的模型，我每次训练测试的结果都不一样，我不知道这个问题出现在了哪里。（对于UNet+AsymBi，我直接运行你的代码，也未能得到和你一样的测试结果。）
第2个问题就是：为什么您复现的代码的测试指标与原作者论文中的指标相差这么多呢？？？（尽管这里面可能是因为初始化和优化函数不同有点关系，但是基本结构没有错的前提下，仍然觉得文章与原作者的指标差异有点大）

**Comment by Tianfang-Zhang** [comment]
第一个问题：可能是SIRST这个数据集体量太小，模型随机跳动比较大。我在训练时也遇到了同样的问题；
第二个问题：与原论文差别较大可能有几种原因：1）ResNet实现与MXNet不同；2）lr下降是没个epoch下降，而不是没个iter；3）数据量小带来的随机跳动。
最近没有对项目进行，对不起
望对您有帮助！

**Comment by tongxiaozhong14** [comment]
非常感谢你在百忙之中能够抽空回复我，请问可以添加你的联系方式和您交流一下吗？？？
或者还想请教你一下，比如他这种的随机跳动比较大的话，应该尝试进行几次会比较合适呢？？然后选取最好的一次的结果吗？？


| |
童小钟
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年4月5日 22:34，Carleton ***@***.***> 写道：

第一个问题：可能是SIRST这个数据集体量太小，模型随机跳动比较大。我在训练时也遇到了同样的问题；
第二个问题：与原论文差别较大可能有几种原因：1）ResNet实现与MXNet不同；2）lr下降是没个epoch下降，而不是没个iter；3）数据量小带来的随机跳动。
最近没有对项目进行，对不起
望对您有帮助！

**Comment by Sam-Yuan** [comment]
您好，抱歉打扰一下，请问一下使用您提供的模型Epoch-225_IoU-0.7152_nIoU-0.7281，在训练集上做测试只能得到Best IoU: 0.65776, best nIoU: 0.66912的效果，是为啥呀？训练集也没有shuffle，也没有数据增强，按理说是不是应该和您的效果是一样的呢？感谢回复

**Comment by Tianfang-Zhang** [comment]
你好，建议可以多尝试几次，数据集小的确会带来比较大的随机性。
另，训练集是需要shuffle的，不然可能会导致过拟合

**Comment by Sam-Yuan** [comment]
好的！谢谢您！！



---原始邮件---
发件人: "Carleton ***@***.***&gt;
发送时间: 2021年4月20日(周二) 晚上9:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tianfang-Zhang/acm-pytorch] 复现代码出现问题？？ (#1)




 
你好，建议可以多尝试几次，数据集小的确会带来比较大的随机性。
 另，训练集是需要shuffle的，不然可能会导致过拟合

**Comment by qianqian321** [comment]
> 亲爱的作者，非常感谢你分享acm的pytorch版本的代码？但是我将你的代码下载之后，在我的电脑上面复现，却出现了几个问题？？你可以给个联系方式吗？？我们一起探讨一下。如果不方便的话，您可以在github上面给我解答吗？？？ 第1个问题就是：运行您的代码，同样的模型，我每次训练测试的结果都不一样，我不知道这个问题出现在了哪里。（对于UNet+AsymBi，我直接运行你的代码，也未能得到和你一样的测试结果。） 第2个问题就是：为什么您复现的代码的测试指标与原作者论文中的指标相差这么多呢？？？（尽管这里面可能是因为初始化和优化函数不同有点关系，但是基本结构没有错的前提下，仍然觉得文章与原作者的指标差异有点大）

您好，请问您复现出pytorch版本的ACM了吗
