### ISSUE TITLE
只适用ResUnet的问题

### ISSUE THREAD

**Issue by KeanuWongves** [Tianfang-Zhang/acm-pytorch#2]
您好，我想请问一下，你有没有试过只适用一些通用的网络，比如Unet++之类的，我尝试用Unet++ Resnet50来跑，但是各项指标始终都是0，看了一下，所有的点都被认为成了是背景。我想做做适用ACM前后的对比实验，所以想请教一下您有没有做过这方面的实验

**Comment by Tianfang-Zhang** [comment]
1. 在这个工程上没有使用通用的网络，但现在已经有一些通用网络的论文发出来，比如[AGPCNet](https://github.com/Tianfang-Zhang/AGPCNet)使用的resnet18和resent34.
2. 各项指标都为0，可能需要调整学习率、损失函数、优化器等参数。

**Comment by q671383789** [comment]
你好，我看了AGPCNet 我也在做红外小目标，很好奇 因为sirst的大小是不一样的，看到你是把图片加了边框然后旋转，有没有尝试过直接随机缩放之后 再裁剪到相同的大小呢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Carleton ***@***.***&gt;; 
发送时间: 2021年12月8日(星期三) 下午5:38
收件人: ***@***.***&gt;; 
抄送: "系要听Rock &amp; ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tianfang-Zhang/acm-pytorch] 只适用ResUnet的问题 (Issue #2)





  
在这个工程上没有使用通用的网络，但现在已经有一些通用网络的论文发出来，比如AGPCNet使用的resnet18和resent34.
 
各项指标都为0，可能需要调整学习率、损失函数、优化器等参数。
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KeanuWongves** [comment]
@Tianfang-Zhang 你好，我也在做红外小目标，也看了你的AGPCNet，但是为什么在AGPCNet里面没有用这个的dataloader方法呢，就是直接随机缩放后再进行裁剪。因为这样的读数据方式，我在原始的ResnetFCN上就取得了很高的结果。

**Comment by Tianfang-Zhang** [comment]
一开始在AGPCNet中做数据增广的目的是通过增加数据量来稳定训练，使每次的结果差距不要太大（这可能是有效的，但并没有进行实验验证）。
另外，小目标的像素很少，网络预测出现一个像素的偏差可能会对指标产生比较大的影响。这仍然是一个比较大的问题。

**Comment by KeanuWongves** [comment]
想请教一下，我刚入行，我不知道在eval的时候对于mask也进行放大的方式在语义分割中是否合理？对比分类任务，这毕竟是一个像素级的任务。
那么是否应该在验证的时候把网络预测的输出再resize到原来的大小 跟原始的mask进行比较这样更合呢？有必要进行这项操作吗



------------------ 原始邮件 ------------------
发件人: Carleton Spark ***@***.***&gt;
发送时间: 2021年12月16日 01:20
收件人: Tianfang-Zhang/acm-pytorch ***@***.***&gt;
抄送: q671383789 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Tianfang-Zhang/acm-pytorch] 只适用ResUnet的问题 (Issue #2)





 
一开始在AGPCNet中做数据增广的目的是通过增加数据量来稳定训练，使每次的结果差距不要太大（这可能是有效的，但并没有进行实验验证）。
 另外，小目标的像素很少，网络预测出现一个像素的偏差可能会对指标产生比较大的影响。这仍然是一个比较大的问题。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Tianfang-Zhang** [comment]
我认为只要训练集和测试集都放大，应该问题不大

**Comment by KeanuWongves** [comment]
好的 谢谢你 好兄弟，不过你也太卷了 上一封半夜一点多回，这一个早上7点回



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Carleton ***@***.***&gt;; 
发送时间: 2021年12月18日(星期六) 上午7:13
收件人: ***@***.***&gt;; 
抄送: "系要听Rock &amp; ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tianfang-Zhang/acm-pytorch] 只适用ResUnet的问题 (Issue #2)





 
我认为只要训练集和测试集都放大，应该问题不大
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Tianfang-Zhang** [comment]
大兄弟不是我卷，是我在国外，有时差啊

**Comment by KeanuWongves** [comment]
哈哈哈哈 笑死 好兄弟 加油





------------------ 原始邮件 ------------------
发件人: Carleton Spark ***@***.***&gt;
发送时间: 2021年12月18日 21:51
收件人: Tianfang-Zhang/acm-pytorch ***@***.***&gt;
抄送: q671383789 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Tianfang-Zhang/acm-pytorch] 只适用ResUnet的问题 (Issue #2)





 
大兄弟不是我卷，是我在国外，有时差啊
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KeanuWongves** [comment]
@Tianfang-Zhang  好兄弟能不能恰个联系方式，有些东西想找你讨论请教一下，感激不尽

**Comment by Tianfang-Zhang** [comment]
github主页上的个人主页有邮箱哈～
